# Accuracy Function Description

This notebook contains 2 metrics to measure accuracy:

**1) Index Matching: checking if each note that needs to be played occurs at the correct pitch and duration.**

**2) Window Matching: checking if each note that needs to be played occurs within a user-specified window (window size is a parameter) with the correct pitch and duration.**

# Function:
```
accuracy_window(prediction, label, window_size)
```

The input arguments are as follows:


```
#prediction: a 2D tensor of dimension 88 × 620 
#label: a 2D tensor of dimension 88 × 620
#window_size: an **odd positive integer** in which the column of interest is the middle of the window. 

The default is 1 (for index to index matching) 
Therefore, if we want perfect index matching, we do not need to set an argument for the window_size

#note: for the prediction and label arrays, we have 88 rows to represent the 88 keys in which each column represents the notes being played during each frame (620 frames) 
```




In [225]:
import torch 
import numpy as np

In [227]:
def accuracy(prediction, label, window_size = 1):
  #initialize count
  count = 0
  #check if window_size is an integer
  #convert each 2D tensor into a 2D numpy array
  pred_np = prediction.numpy()
  label_np = label.numpy() 
  #check that the dimensions of the prediction and the label are the same
  if pred_np.shape != label_np.shape:
    print("Error- prediction and label sizes don't match!")
    return
  #check that window_size is a positive odd integer 
  if window_size <= 0:
    print("Error- window_size is not positive!")
    return
  elif isinstance(window_size, int) != True:
    print("Error- window_size is not an integer!")
    return
  elif isinstance(window_size, int) == True:
    if window_size % 2 == 0:
      print("Error- window_size is not odd!")
      return
  #find the number of frames of each file
  col = pred_np.shape[1]
  #check if the values in each column of the prediction are the same for the label within the window_size
  for i in range(col):
    #case where window_size is out of bounds (beginning case)
    if i >=0 and i < int(window_size/2):
      lower_lim = 0
      upper_lim = i + int(window_size/2)
    #case where window_size is out of bounds (end case)
    elif i >= col - int(window_size/2) and i <= col:
      lower_lim = i - int(window_size/2)
      upper_lim = col - 1
    else:
      lower_lim = i - int(window_size/2)
      upper_lim = i + int(window_size/2)
    window_arr = label_np[:, lower_lim:upper_lim + 1]
    if (np.transpose(pred_np)[i:i+1].tolist()[0] in np.transpose(window_arr).tolist()) == True: 
      count += 1
  return count/col

In [229]:
accuracy(a, b)

1.0

Additional function that works but is not required

In [90]:
def accuracy_idx(prediction, label):
  #convert each 2D tensor into a 2D numpy array
  pred_np = prediction.numpy()
  label_np = label.numpy()
  #check that the dimensions of the prediction and the label are the same
  if pred_np.shape != label_np.shape:
    print("Error- prediction and label sizes don't match!")
    return
  #find the number of frames of each file
  col = pred_np.shape[1]
  #check if the values in each column of the prediction are the same for the label
  acc_bool = np.all(pred_np == label_np, axis = 0)
  count = sum(acc_bool)
  return (count/col)

# Some Test Cases (can ignore)

In [222]:
a = [[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18], [19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30]]
print(a)
a = torch.tensor(a)
print(a)

#b = [[0, 1, 4, 0, 0, 3], [0, 7, 10, 0, 0, 9], [0, 13, 16, 0, 0, 15], [0, 19, 22, 0, 0, 21], [0, 25, 28, 0, 0, 27]]
b = [[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18], [19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30]]
print(b)
b = torch.tensor(b)
print(b)

[[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18], [19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30]]
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]])
[[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18], [19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30]]
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]])


In [27]:
a = torch.ones(5, 7, dtype=torch.int16)
print(a)
b = torch.zeros(5, 7, dtype=torch.int16)
print(b)

tensor([[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]], dtype=torch.int16)
tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]], dtype=torch.int16)
